### ISSUE TITLE
Update chrome install URL to `https://www.google.com/chrome/?platform=linux`

### ISSUE THREAD

**Issue by hikalium** [zigen-project/zwindowsystem-web#33]
it would be nice if the link for chrome is updated to `https://www.google.com/chrome/?platform=linux` instead of `https://www.google.com/chrome/` on https://www.zwin.dev/ja/getting_started/installation , since a user may follow the steps from a remote, non-linux machine (e.g. macOS)

**Comment by Aki-7** [comment]
You're right! Thank you!
